# NOTE: Used for both 6 and 7 dof bots. The joint_7 value will be unused for 6 dof bots
# Using the "Home" pose from ada.srdf as a valid starting configuration
joint_1: 0.0
joint_2: 0.26
joint_3: 3.14
joint_4: -2.27
joint_5: 0.0
joint_6: 0.96
joint_7: 1.57
